# Generated by Django 2.2.28 on 2023-04-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_bookings_currency_bookings_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='adhar_card',
            new_name='social_security_number',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='pan_card',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
